format = """\
[](bg:color6 fg:color2)\
[󰣇 ](bg:color2 fg:color1)\
[](fg:color2 bg:color1)\
[](fg:color1 bg:color1)\
$directory\
[](fg:color1 bg:color2)\
$git_branch\
$git_status\
$git_metrics\
[](fg:color2 bg:color6)\
\n$character\
"""

palette = 'colors'

[palettes.colors]
mustard = '#af8700' # optional spare
color1 = '{{colors.primary_fixed_dim.default.hex}}'
color2 = '{{colors.on_primary.default.hex}}'
color3 = '{{colors.on_surface_variant.default.hex}}'
color4 = '{{colors.surface_container.default.hex}}'
color5 = '{{colors.on_primary.default.hex}}'
color6 = '{{colors.surface_dim.default.hex}}'
color7 = '{{colors.surface.default.hex}}'
color8 = '{{colors.primary.default.hex}}'
color9 = '{{colors.tertiary.default.hex}}'

[directory]
format = "[ $path ]($style)"
style = "fg:color2 bg:color1"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
format = '[ $symbol$branch(:$remote_branch) ]($style)'
symbol = "  "
style = "fg:color1 bg:color2"

[git_status]
format = '[$all_status]($style)'
style = "fg:color1 bg:color2"

[git_metrics]
format = "([+$added]($added_style))[]($added_style)"
added_style = "fg:color1 bg:color2"
deleted_style = "fg:color1 bg:color2"
disabled = true

[hg_branch]
format = "[ $symbol$branch ]($style)"
symbol = " "

[cmd_duration]
format = "[ $duration ]($style)"
style = "fg:color2 bg:color1"

[character]
success_symbol = '[ ➜](bold green) '
error_symbol = '[ ✗](fg:#E84D44) '

[time]
disabled = false
time_format = "%R"
style = "bg:color6"
format = '[[ 󱑍 $time ](bg:color1 fg:color2)]($style)'
