format = """\
[](bg:color6 fg:color2)\
[󰣇 ](bg:color2 fg:color1)\
[](fg:color2 bg:color1)\
[](fg:color1 bg:color1)\
$directory\
[](fg:color1 bg:color2)\
$git_branch\
$git_status\
$git_metrics\
[](fg:color2 bg:color6)\
\n$character\
"""

palette = 'colors'

[palettes.colors]
mustard = '#af8700' # optional spare
color1 = '#cebdfe'
color2 = '#35275d'
color3 = '#cac4cf'
color4 = '#211f24'
color5 = '#35275d'
color6 = '#141218'
color7 = '#141218'
color8 = '#cebdfe'
color9 = '#efb8c8'

[directory]
format = "[ $path ]($style)"
style = "fg:color2 bg:color1"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
format = '[ $symbol$branch(:$remote_branch) ]($style)'
symbol = "  "
style = "fg:color1 bg:color2"

[git_status]
format = '[$all_status]($style)'
style = "fg:color1 bg:color2"

[git_metrics]
format = "([+$added]($added_style))[]($added_style)"
added_style = "fg:color1 bg:color2"
deleted_style = "fg:color1 bg:color2"
disabled = true

[hg_branch]
format = "[ $symbol$branch ]($style)"
symbol = " "

[cmd_duration]
format = "[ $duration ]($style)"
style = "fg:color2 bg:color1"

[character]
success_symbol = '[ ➜](bold green) '
error_symbol = '[ ✗](fg:#E84D44) '

[time]
disabled = false
time_format = "%R"
style = "bg:color6"
format = '[[ 󱑍 $time ](bg:color1 fg:color2)]($style)'
